# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: hera-demo-server
  name: hera-demo-server
  namespace: ozhera-namespace
spec:
  replicas: 1

  selector:
    matchLabels:
      app: hera-demo-server
  template:
    metadata:
      labels:
        app: hera-demo-server
    spec:
      imagePullSecrets:
      - name: mione-opensource-credential
      containers:
      - image: herahub/opensource-pub:ozhera-demo-server-server-2.2.5-incubating-beta-v1
        name: hera-demo-server
        env:
          - name: MIONE_PROJECT_NAME
            value: 1-hera-demo-server
          - name: MIONE_PROJECT_ENV_NAME
            value: dev
          - name: MIONE_PROJECT_ENV_ID
            value: '1'
        ports:
        - containerPort: 9995
          protocol: TCP
        volumeMounts:
          - name: log-path
            mountPath: /home/work/log
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 2500Mi

      - name: log-agent
        image: herahub/opensource-pub:log-agent-server-2.2.5-incubating-beta-v1
        env:
          - name: nacosAddr
            value: nacos.hera-namespace:80
        volumeMounts:
        - mountPath: "/home/work/log"
          name: log-path
        resources:
          limits:
            cpu: '300m'
            memory: 1Gi
      volumes:
      - name: log-path
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: hera-demo-server
  namespace: ozhera-namespace
spec:
  ports:
    - port: 9995
      targetPort: 9995
      protocol: TCP
  selector:
    app: hera-demo-server
---
apiVersion: v1
kind: Service
metadata:
  name: hera-demo-server-grpc
  namespace: ozhera-namespace
spec:
  ports:
    - port: 8998
      targetPort: 8998
      protocol: TCP
  selector:
    app: hera-demo-server