FROM openjdk:21-jdk-bookworm
COPY ./target/ozhera-webhook-server-1.0-jdk21.jar /home/work/hera-webhook-server-1.0-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","-Duser.timezone=Asia/Shanghai","/home/work/hera-webhook-server-1.0-SNAPSHOT.jar","&&","tail","-f","/dev/null"]
